kxtractui/kxtractui/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('ui/', include('ui.urls')),
    path('admin/', admin.site.urls),
]

kxtractui/ui/urls.py
from django.urls import path

from . import views

urlpatterns = [
  path('', views.index, name='index'),
  path('podcasts/', views.podcasts, name='podcasts'),
  path('episodes/', views.episodes, name='episodes'),
  path('episode/<int:episode_id>/transcription/', views.transcription, name='transcription')

]

kxtractui/ui/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from django.conf import settings
from django.utils.translation import gettext_lazy as _


class Podcast(models.Model):
    name = models.CharField(max_length=256)
    rss_url = models.CharField(max_length=1024)

    class Meta:
        managed = getattr(settings, 'UNDER_TEST', False)
        db_table = 'podcast'

    def __str__(self):
        return self.name


class Episode(models.Model):
    processing_staus_type = (
        ('0', "Downloaded"),
        ('1', "Transcription In Process"),
        ('2', "Transcription Complete"),
        ('3', "Error"),
    )
    podcast = models.ForeignKey('Podcast', models.DO_NOTHING, null=True)
    id = models.IntegerField(primary_key=True, blank=True)
    episode_name = models.CharField(max_length=128)
    filesize_kb = models.IntegerField(blank=True, null=True)
    origin_url = models.CharField(max_length=256)
    s3_url = models.CharField(max_length=256)
    processing_status = models.CharField(choices=processing_staus_type, max_length=64)

    class Meta:
        managed = getattr(settings, 'UNDER_TEST', False)
        db_table = 'episode'
        unique_together = (('podcast', 'episode_name'),)

    def __str__(self):
        return self.episode_name


class Subscription(models.Model):
    user_id = models.CharField(max_length=64)
    podcast = models.ForeignKey(Podcast, models.DO_NOTHING, null=True)

    class Meta:
        managed = getattr(settings, 'UNDER_TEST', False)
        db_table = 'subscription'

    def __str__(self):
        return "UserId :{} --> Podcast Name: {}.".format(self.user_id, self.podcast.name)


class Transcription(models.Model):
    episode = models.OneToOneField(Episode, models.DO_NOTHING, null=True)
    s3_transcription_download_location = models.CharField(max_length=4096, blank=True, null=True)
    raw_transcription = models.TextField(blank=True, null=True)
    formatted_transcription = models.TextField(blank=True, null=True)

    class Meta:
        managed = getattr(settings, 'UNDER_TEST', False)
        db_table = 'transcription'

    def __str__(self):
        return "Transcription for Episode Name : {}".format(self.episode.episode_name)

kxtractui/ui/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .models import Podcast, Episode


def index(request):
    return HttpResponse("Hello World - you are at the KXtract UI Home page")


def podcasts(request):
    current_podcasts = Podcast.objects.order_by('id')
    context = {
        'current_podcasts': current_podcasts,
    }
    return render(request, 'podcasts/index.html', context)


def episodes(request):
    episodes = Episode.objects.order_by('id')
    context = {
        'episodes': episodes,
    }
    return render(request, 'episodes/index.html', context)


def transcription(request):
    return HttpResponse("TBD3")

kxtractui/ui/templates/episodes/index.html
<html>
<title>Episode List</title>
<head>
        <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>
<body>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

{% if episodes %}
<table class="table table-striped table-hover table-sm">
    <thead class="thead-dark">
        <th>Id</th>
        <th>Episode Name</th>
        <th>Processing Status</th>
        <th>Episode Source URL</th>
        <th>Audio Filesize</th>
        <th>S3 URL</th>
    </thead>
    {% for e in episodes %}
    <tr {% if e.get_processing_status_display == 'Transcription Complete' %}class="table-success"{% elif e.get_processing_status_display == 'Error' %}class="table-danger"{% endif %}>
        <td>{{ e.id }}</td>
        <td>{{ e.episode_name }}</td>
        <td>{{ e.get_processing_status_display}}</td>
        <td><a href="{{e.origin_url}}">Origin URL</a></td>
        <td>{{e.filesize_kb}}</td>
        <td>{{e.s3_url}}</td>
    </tr>
    {% endfor %}

</table>
{% else %}
    <p>No episodes are available.</p>
{% endif %}
</body>
</html>

kxtractui/ui/templates/podcasts/index.html
<html>
<title>Podcast List</title>
<body>
{% if current_podcasts %}
    <ul>
    {% for p in current_podcasts %}
        <li>{{ p.name }}</li>
    {% endfor %}
    </ul>
{% else %}
    <p>No podcasts are available.</p>
{% endif %}
</body>
</html>